server {
    listen 8080;
    host 127.0.0.1;
    server_name main_server.1337;
    root ./www/;
    index index.html;
    autoindex off;
    client_max_body_size 100M;
    error_page 404 /error/404.html;
    error_page 400 403 405 413 /error/error.html;
    error_page 500 502 503 504 /error/error.html;

    location / {
        allow_methods GET;
        index empty.html;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100M;
        upload_store ./uploads;
        autoindex on;
    }

    location /directory/ {
        allow_methods GET;
        index youpi.bad_extension;
        root ./YoupiBanane;
        autoindex off;
    }

    location idk {
        allow_methods POST;
        cgi_handler .bla ./cgi-tester;
        autoindex off;
    }

}
